# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' 
  # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --only=prod
    npm run build
    yarn install
    npm run compile
    tsc --target ES6 --strict true --project tsconfigs/production.json
  displayName: 'npm install and build'

- task: Npm@1
  inputs:
    customEndpoint: <Name of npm service connection>

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'